[package]
name = "rusttest"
version = "0.1.0"
edition = "2021"

[dependencies]
gl = "0.14.0"
sdl2 = { version = "0.35.0", features = ["bundled", "static-link"] }
thiserror = "1.0.31"

[build-dependencies]
walkdir = "2.1"